export const LOGIN_USER_LOGIN = 'LOGIN_USER_LOGIN'
export const LOGIN_USER_LOGIN_FULFILLED = 'LOGIN_USER_LOGIN_FULFILLED'
export const LOGIN_USER_LOGOUT='LOGIN_USER_LOGOUT';
// export const LOGIN_CHECK_IS_USER_EXIST='LOGIN_CHECK_IS_USER_EXIST';
// export const LOGIN_REGISTER_USER='LOGIN_REGISTER_USER';
